from enum import Enum

WEAPON = Enum('Weapon', [('Bullet', 1), ('Laser', 2), ('Max', 2)])

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
CENTER_X = SCREEN_WIDTH / 2
CENTER_Y = SCREEN_HEIGHT / 2
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MIN_SPEED = 200
PLAYER_MAX_SPEED = 400
PLAYER_ACCELERATION = 10
BULLET_SHOT_RADIUS = 5
BULLET_SHOOT_SPEED = 500
LASER_SHOOT_SPEED = 800
LASER_LENGTH = 20
PLAYER_INITIAL_LIVES = 3
MAX_SAFE_DISTANCE = 20
SPLIT_ASTEROID_VELOCITY_MODIFIER = 1.2
NUM_ASTEROID_EDGES = 20
ASTEROID_EDGES_VARIATION = 5
POWERUP_SPAWN_RATE = 5
POWERUP_SHRINK_RATE = 0.05
POWERUP_RADIUS = 20
SHOT_SPEED_POWERUP_RATE = 2
POWERUP_TIME_GIVEN = 5
POWERUP_HEIGHT_OFF_SCREEN_MARGIN = 3
BULLET_SHOT_COOLDOWN = 0.3
LASER_SHOT_COOLDOWN = 1.0
TAB_BTN_COOLDOWN = 0.2